name: Build Windows Release

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    strategy:
      matrix:
        config: [Release]
        arch: [x64]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.arch }}
        
    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.20'
        
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=${{ matrix.config }}
        
    - name: Build
      run: |
        cd build
        nmake
        
    - name: Verify build
      run: |
        if (Test-Path "build/TeamsKeeper.exe") {
          Write-Host "✅ Build successful - TeamsKeeper.exe created"
          Get-Item "build/TeamsKeeper.exe" | Select-Object Name, Length, LastWriteTime
        } else {
          Write-Host "❌ Build failed - TeamsKeeper.exe not found"
          Get-ChildItem build -Recurse
          exit 1
        }
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: TeamsKeeper-Windows-${{ matrix.arch }}-${{ matrix.config }}
        path: build/TeamsKeeper.exe
        retention-days: 30
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: build/TeamsKeeper.exe
        name: TeamsKeeper ${{ github.ref_name }}
        body: |
          ## TeamsKeeper ${{ github.ref_name }}
          
          🚀 **Windows 11 System Tray Application**
          
          ### Features
          - ✅ Keep system awake (prevent sleep)
          - ✅ Keep Microsoft Teams status green
          - ✅ Clean system tray interface
          - ✅ Toggle controls via right-click menu
          
          ### Download
          - **TeamsKeeper.exe** - Ready to run on Windows 11/10
          
          ### Usage
          1. Download `TeamsKeeper.exe`
          2. Run the executable
          3. Look for the green/gray icon in your system tray
          4. Right-click to access settings
          
          ### System Requirements
          - Windows 10/11 (x64)
          - No additional dependencies required
          
          ---
          Built with GitHub Actions & Visual Studio 2019 🤖
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}